### ISSUE TITLE
Interpreting the QUAL column 

### ISSUE THREAD

**Issue by zhemingfan** [HKU-BAL/ClairS#1]
Hi @aquaskyline and @zhengzhenxian,

Thank you for releasing an early access version of ClairS. Just playing around with this, I had a quick clarification question:

I was wondering what the QUAL column value signifies. Broadly, I believe the "QUAL value reflects how confident we are that a site displays some kind of variation considering the amount of data available", in this case, is it the confidence that a call is somatic? And how do you generate this QUAL score? 

Thanks.

**Comment by aquaskyline** [comment]
It's the phred-scale probability of the variant being a somatic variant over a germline or a reference. The calculation is a bit more complicated since we use the arithmetic average of the probability by two calling models. Those post-calling filtered variants are reassigned with quality 0.

**Comment by zhemingfan** [comment]
Thank you!
