### ISSUE TITLE
question: model for 5khz data

### ISSUE THREAD

**Issue by bakeronit** [HKU-BAL/ClairS#10]
Hi Ruibang,

Since nanopore sequencing software updated to 5kHz sampling mode, I am wondering if there will be a pre-trained model for 5kHz data. Can I still use --platform ont_r10 (ont_r104_e81_sup_g5015) for now? Thank you.

Cheers
Jia

**Comment by aquaskyline** [comment]
No, 5khz needs a different model. We will release a draft 5khz model soon. A full 5khz model trained on more samples is also on our schedule. At some point, ONT will also start providing ClairS model for new chemistries.

**Comment by bakeronit** [comment]
That makes sense. Thank. you.

**Comment by zhengzhenxian** [comment]
@bakeronit 

We have released ClairS v0.1.3 with the ONT Dorado 5kHZ(use -p `ont_r10_dorado_5khz`) model included. Pls kindly try and let us if you have any issue, thanks!

**Comment by bakeronit** [comment]
That's great! will have a try. Thank you.
