### ISSUE TITLE
Empty VCF produced by ClairS

### ISSUE THREAD

**Issue by rowanhowellGE** [HKU-BAL/ClairS#2]
Hi,

I ran a set of 21 tumour-normal pairs. All jobs completed successfully but 5 runs returned empty VCFs. Looking into the log file I found the following:

![image](https://user-images.githubusercontent.com/108926253/219718265-29754859-2ed5-49ef-a6aa-fd73380b13b2.png)

I am running ClairS v0.0.1 from dockerhub, accessed on January 23rd. 

Thanks,
Rowan

**Comment by zhengzhenxian** [comment]
Hi, Rowan,

Thanks so much for reporting the issue. We have fixed the bug and please try to re-pull the docker image(You might need to remove your local image first using `dcoker rmi hkubal/clairs:latest` ).  If the issue persists, please let us know, thanks!

Zhenxian

**Comment by rowanhowellGE** [comment]
Thanks, the latest version produced proper VCF files with variants in them.

**Comment by gbanco4** [comment]
Hi there, I just had this same issue with version 0.4.1. I did my installation through conda and not docker. I ran ClairS v0.4.1 on 11 samples and got empty vcf files for all. The log shows that the steps for sorting VCFs and Merge & sort VCFs failed.

`[INFO] Merge Full-alignment VCFs
[INFO] RUN THE FOLLOWING COMMAND:
pypy3 /projects/rmorin_scratch/giuliano_nanopore/environments/ClairS/clairs.py sort_vcf --ref_fn /projects/rmorin/projects/gambl-repos/gambl-gbanco/ref/lcr-modules-references/genomes/hg38/genome_fasta/genome.fa --contigs_fn /projects/rmorin_scratch/giuliano_temp/sample/tmp/CONTIGS --input_dir /projects/rmorin_scratch/giuliano_temp/sample/tmp/vcf_output --vcf_fn_prefix fa_ --output_fn /projects/rmorin_scratch/giuliano_temp/sample/tmp/vcf_output/full_alignment.vcf

[INFO] Sorting VCFs...
[93m[WARNING] No vcf file found, output empty vcf file[0m

[INFO] STEP 4: Haplotype filtering
[INFO] RUN THE FOLLOWING COMMAND:
( time pypy3 /projects/rmorin_scratch/giuliano_nanopore/environments/ClairS/clairs.py haplotype_filtering --tumor_bam_fn /projects/rmorin_scratch/giuliano_temp/sample/tmp/clair3_output/phased_output/tumor_ --ref_fn /projects/rmorin/projects/gambl-repos/gambl-gbanco/ref/lcr-modules-references/genomes/hg38/genome_fasta/genome.fa --germline_vcf_fn /projects/rmorin_scratch/giuliano_temp/sample/tmp/clair3_output/clair3_tumor_output/merge_output.vcf.gz --pileup_vcf_fn /projects/rmorin_scratch/giuliano_temp/sample/tmp/vcf_output/pileup.vcf --full_alignment_vcf_fn /projects/rmorin_scratch/giuliano_temp/sample/tmp/vcf_output/full_alignment.vcf --output_dir /projects/rmorin_scratch/giuliano_temp/sample/tmp/vcf_output --samtools samtools --pypy3 pypy3 --parallel parallel --threads 24 ) 2>&1 | tee /projects/rmorin_scratch/giuliano_temp/sample/logs/4_HAP_FILTER.log

Total input calls: 0, filtered by haplotype match 0

real	1m28.833s
user	1m14.207s
sys	0m17.506s

[INFO] STEP 5: Merge and sort VCF
[INFO] RUN THE FOLLOWING COMMAND:
( time pypy3 /projects/rmorin_scratch/giuliano_nanopore/environments/ClairS/clairs.py merge_vcf --ref_fn /projects/rmorin/projects/gambl-repos/gambl-gbanco/ref/lcr-modules-references/genomes/hg38/genome_fasta/genome.fa --pileup_vcf_fn /projects/rmorin_scratch/giuliano_temp/sample/tmp/vcf_output/pileup_filter.vcf --full_alignment_vcf_fn /projects/rmorin_scratch/giuliano_temp/sample/tmp/vcf_output/full_alignment_filter.vcf --output_fn /projects/rmorin_scratch/giuliano_temp/sample/sample_ClairS_test_calls.vcf --platform ont --qual 8 --sample_name SAMPLE --enable_indel_calling False --prefer_recall False --cmdline /projects/rmorin_scratch/giuliano_temp/sample/tmp/CMD ) 2>&1 | tee /projects/rmorin_scratch/giuliano_temp/sample/logs/5_MV.log

[93m[WARNING] No vcf file found, please check the setting[0m
[93m[WARNING] No variant found, please check the setting[0m
[INFO] Full-alignment variants filtered by pileup:  0`
