### ISSUE TITLE
sh files for data preprocessing

### ISSUE THREAD

**Issue by shiying-sxu** [HKU-BAL/ClairS#20]
Can you share the sh files for data preprocessing and model training? Like Clair3.

Thank you!

**Comment by zhengzhenxian** [comment]
Thanks for your interest. We are still completing the whole training workflow, many validations and optimizations are still going on on our sides and with our collaborators. 

We expect to be more confident before we can release the training data-generating scripts. At the moment, you might refer to the data generation procedures elaborated in ClairS' preprint.
