### ISSUE TITLE
Question in training data label generation code - get_candidates.py

### ISSUE THREAD

**Issue by quito418** [HKU-BAL/ClairS#21]
Dear ClairS Team,

While reviewing the code at the following link: https://github.com/HKU-BAL/ClairS/blob/c464c98c61f594489e385b8bb67c32518dce59f8/src/get_candidates.py#L348 
I noticed a potential issue related to the `find_candidate_match` function. 
It appears that the function may be utilizing the tumor alt_dict instead of the normal alt_dict.
Could you please take a moment to verify this?

Thank you for your time and support!

Best regards,

**Comment by zhengzhenxian** [comment]
Hi, @quito418,

Billions thanks for reporting this! Should be normal alt_dict(paired_alt_dict). I guess it would only exclude a small proportion of candidates in training. We will try to add those candidates to training to further verify the results.

Zhenxian

**Comment by quito418** [comment]
Thanks, @Zhenxian! Looking forward to the release of the ClairS.
