### ISSUE TITLE
tmp folders not being deleted after calling

### ISSUE THREAD

**Issue by A-Goretsky** [HKU-BAL/ClairS#24]
The `tmp` folders created by ClairS are not deleted after the run is finished, or if they are, it is not consistent. They take up a significant amount of space and can unexpectedly fill up workspaces.

**Comment by zhengzhenxian** [comment]
@A-Goretsky 

We provide an option (`--remove_intermediate_dir`) to remove the `tmp` DIR after calling, you can enable the option before running the workflow.

**Comment by A-Goretsky** [comment]
Missed that, thank you.
