### ISSUE TITLE
ClairS quits with exit code 0 but no output, no error logged

### ISSUE THREAD

**Issue by nparmalee** [HKU-BAL/ClairS#25]
I'm using ClairS on three samples right now. Two have been running since last night, no issue yet. The third quits within seconds of launching the job with exit code 0 but no output is written. The directory structure is created in the output file. No errors are written in the log. This job is using a custom reference but I get the same behavior with these files if I substitute hg38 as the reference. Is there a debug flag or something I can use to tell me what is going wrong? This is the code I'm running. Any help would be greatly appreciated.

./run_clairs \
  -T /home/nparma/eee_bams_dsa/DSA_hifiasm_60x/ONT/COLO829-T_PS00361.all.sorted.bam \
  -N /home/nparma/eee_bams_dsa/DSA_hifiasm_60x/ONT/COLO829-BL_PS00342.all.sorted.bam \
  -R /home/nparma/eee_bams_dsa/references/dsa60/COLO829-BL_60X_hifisam_merged_haplotypes.fasta \
  -t 4 \
  -p ont_r10_dorado_sup_5khz \
  -o /home/nparma/eee_bams_dsa/myanalysis/clairs/T/dsa/clairsout

**Comment by zhengzhenxian** [comment]
@nparmalee 

Could you share  `logs` directory and  `run_clairs.log` log file in your output dir `/home/nparma/eee_bams_dsa/myanalysis/clairs/T/dsa/clairsout` for us to pinpoint the issue?

My email address is zxzheng@cs.hku.hk, thanks.

**Comment by nparmalee** [comment]
Thanks so much for your quick reply.

Here are the contents of the run_clairs.log file:

[COMMAND] /gpfs/home/nparma/programs/ClairS/run_clairs --tumor_bam_fn /home/nparma/eee_bams_dsa/DSA_hifiasm_60x/ONT/COLO829-T_PS00361.all.sorted.bam --normal_bam_fn /home/nparma/eee_bams_dsa/DSA_hifiasm_60x/ONT/COLO829-BL_PS00342.all.sorted.bam --ref_fn /home/nparma/eee_bams_dsa/references/dsa60/COLO829-BL_60X_hifisam_merged_haplotypes.fasta --threads 4 --platform ont_r10_dorado_sup_5khz --output_dir /home/nparma/eee_bams_dsa/myanalysis/clairs/T/dsa/clairsout

[INFO] --include_all_ctgs not enabled, use chr{1..22,X,Y} and {1..22,X,Y} by default

**Comment by nparmalee** [comment]
Thanks for pointing me to that log file, I had missed it. I updated the code and so far this is running. This bam file is aligned to a donor specific assembly and I’m not sure how the contains are named so this error makes some sense.

./run_clairs \
  -T /home/nparma/eee_bams_dsa/DSA_hifiasm_60x/ONT/COLO829-T_PS00361.all.sorted.bam \
  -N /home/nparma/eee_bams_dsa/DSA_hifiasm_60x/ONT/COLO829-BL_PS00342.all.sorted.bam \
  -R /home/nparma/eee_bams_dsa/references/dsa60/COLO829-BL_60X_hifisam_merged_haplotypes.fasta \
  -t 4 \
  -p ont_r10_dorado_sup_5khz \
  -o /home/nparma/eee_bams_dsa/myanalysis/clairs/T/dsa/clairsout \
  --include_all_ctgs

**Comment by nparmalee** [comment]
Hello, and thank you for your help earlier. Unfortunately the run finished without producing a vcf file. This is the code I ran. I am attaching the log file. I would really appreciate your help with this. 

Thanks,
Nancy


./run_clairs \
  -T /home/nparma/eee_bams_dsa/DSA_hifiasm_60x/ONT/COLO829-T_PS00361.all.sorted.bam \
  -N /home/nparma/eee_bams_dsa/DSA_hifiasm_60x/ONT/COLO829-BL_PS00342.all.sorted.bam \
  -R /home/nparma/eee_bams_dsa/references/dsa60/COLO829-BL_60X_hifisam_merged_haplotypes.fasta \
  -t 4 \
  -p ont_r10_dorado_sup_5khz \
  -o /home/nparma/eee_bams_dsa/myanalysis/clairs/T/dsa/clairsout \
  --include_all_ctgs

**Comment by xianyu0623** [comment]
Hello, [nparmalee](https://github.com/nparmalee)

I encountered a similar issue and wanted to share a potential solution. Please ensure that a .bai file exists in the same path as your bam file. ClairS relies on the 'samtools mpileup' command for candidate selection, which requires a .bai file. Without it, ClairS will not produce results or log errors, as it does not check stderr.

I hope this helps!
