### ISSUE TITLE
samtools index: failed to open error

### ISSUE THREAD

**Issue by DIPLOMICS-SA** [HKU-BAL/ClairS#28]
Good day,
I am using ClairS-TO using the following command:

singularity exec /apps/chpc/bio/clairs_to/clairs-to_latest.sif run_clairs_to -T BC1.sorted.bam -R GCF_000001405.40_GRCh38.p14_genomic.fna -t 8 -p ont_r10_dorado_hac_4khz --include_all_ctgs --output_dir output-BC1

I however get the following error (I don't get a final .vcf file but I do get many vcf files in the tmp folder):

samtools index: failed to open "/mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/output-BC1/tmp/phasing_output/phased_bam_output/tumor_NT_187421.1.bam": No such file or directory
ERROR in STEP 11, THE FOLLOWING COMMAND FAILED: ( parallel --joblog /mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/output-BC1/logs/phasing_log/parallel_3_haplotag_tumor.log -j 8 /opt/micromamba/envs/clairs-to/bin/longphase haplotag -o /mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/output-BC1/tmp/phasing_output/phased_bam_output/tumor_{1}.bam --reference /mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/GCF_000001405.40_GRCh38.p14_genomic.fna --region {1}  -s /mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/output-BC1/tmp/phasing_output/phased_vcf_output/tumor_phased_{1}.vcf.gz -b /mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/BC1.sorted.bam :::: /mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/output-BC1/tmp/CONTIGS ) 2>&1 | tee /mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/output-BC1/logs/phasing_log/3_tumor_haplotag.log && parallel -j 8 samtools index  -@8 /mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/output-BC1/tmp/phasing_output/phased_bam_output/tumor_{1}.bam :::: /mnt/lustre/groups/CBBI1617/BreastCancer-fastq/SNV-analysis/input/output-BC1/tmp/CONTIGS

Could I please get some assistance on this.

**Comment by JasonCLEI** [comment]
Hi, @DIPLOMICS-SA,

Thanks a lot for your interest on ClairS-TO. It seems that the issue was caused in the LongPhase haplotagging process, but we cannot be certain due to the lack of complete running log. Could you please provide your complete running log of `run_clairs_to.log` file, and we will check the issue for you further. By the way, to quickly obtain a result, you could rerun the program with your own data by adding another option `--phase_tumor False` and check if the issue still exists.

Lei

**Comment by DIPLOMICS-SA** [comment]
Hi @JasonCLEI thank you for getting back to me. please find the attached log file 
[Uploading run_clairs_to.log…]()

**Comment by JasonCLEI** [comment]
Hi, @DIPLOMICS-SA sorry for not seeing the attached log file. Could you please upload it again?

**Comment by DIPLOMICS-SA** [comment]
[run_clairs_to.log](https://github.com/HKU-BAL/ClairS/files/15414810/run_clairs_to.log)

Hopefully this works @JasonCLEI

**Comment by JasonCLEI** [comment]
Hi, @DIPLOMICS-SA,

We have checked your complete running log and found that you are not using the latest image of ClairS-TO, which caused the issue above. You are suggested to re-pull the image and rerun the program with your own data with the latest release of ClairS-TO, and the issue may disappear. Let us know if there are any issues after that. Thanks a lot again for your interest on ClairS-TO.

Lei

**Comment by DIPLOMICS-SA** [comment]
Hi @JasonCLEI so I tried to re install the tool and I still get the same error?

**Comment by JasonCLEI** [comment]
Hi @DIPLOMICS-SA have you tried to delete the original `clairs-to_latest.sif` and then re-pull the latest image of ClairS-TO? If you have done so and still got the error, could you kindly provide your latest running log of `run_clairs_to.log` file?

**Comment by JasonCLEI** [comment]
Hi @DIPLOMICS-SA have you solved this problem at the moment? If you have done so and still got the error, could you kindly provide your latest running log of `run_clairs_to.log` file?
