### ISSUE TITLE
Loci file /opt/conda/envs/clairs/bin/cnv_data/reference_files/loci_files/G1000_loci_hg38_chr1.txt does not appear to exist.

### ISSUE THREAD

**Issue by erdikilic** [HKU-BAL/ClairS#32]
I got this error when I run the following commands;

```
singularity pull clairs.sif docker://hkubal/clairs:latest
singularity exec --bind /truba/home/erdikilic/pacbio_nd_t:/data clairs.sif /opt/bin/run_clairs \
    --platform hifi_revio \
    --ref_fn /data/hg38.fa \
    --tumor_bam_fn /data/hg008-t/HG008-T.bam \
    --normal_bam_fn /data/hg008-n-d/hg008-N-D.bam \
    --sample_name HG008_T \
    --remove_intermediate_dir \
    --include_all_ctgs \
    --enable_indel_calling \
    --enable_clair3_germline_output \
    --enable_verdict \
    --output_dir /data/analysis/clairs \
    --conda_prefix /opt/conda/envs/clairs \
    --threads 2
```
It is still running and din't stop the variant calling. Also, when I check the folder, the loci files exist. 

[7_CGT.log](https://github.com/user-attachments/files/16411672/7_CGT.log)
[run.log](https://github.com/user-attachments/files/16411760/run.log)

**Comment by zhengzhenxian** [comment]
@erdikilic 

Thanks for reporting. Could you try to re-pull our latest docker image using singularity (`singularity pull docker://hkubal/clairs:latest`)?  Pls let us know if the issue persists.

**Comment by erdikilic** [comment]
@zhengzhenxian Are you certain the latest image is current with this update? The most recent tag was pushed 18 days ago.

**Comment by zhengzhenxian** [comment]
@erdikilic When did you pull `clairs.sif` with the error? We have a minor update to fix the CNV reference file path issue two weeks ago when upgrading ClairS from v0.2.0 to v0.3.0. Not sure if you using an outdated docker image, as we cannot repeat your issue with the latest docker image.

**Comment by erdikilic** [comment]
I cleared the cache and repulled the image to ensure I have the latest version, which is v0.3.0. I've started it and am now waiting to see if any errors occur. Thanks for your response, @zhengzhenxian.
