### ISSUE TITLE
Question: Timeline for releasing new models

### ISSUE THREAD

**Issue by lucy924** [HKU-BAL/ClairS#33]
Hi team, I was wondering if you had a rough timeline/estimates for when new ClairS models are released following new ONT basecalling models? 
Specifically, I've basecalled a lot of data using `dna_r10.4.1_e8.2_400bps_sup@v4.3.0` and then discovered it's not yet supported by the ClairS version (at least the current one being used in dorado v1.3.1, and I can't figure out how to confirm which version of ClairS it uses).
I'm wondering whether it's worth rebasecalling all my pod5s with an older model that's supported by ClairS.
Thanks!

**Comment by zhengzhenxian** [comment]
Hi @lucy924,

You might use `--ont_r10_dorado_sup_5khz` in ClairS for your `dna_r10.4.1_e8.2_400bps_sup@v4.3.0` data.

**Comment by zhengzhenxian** [comment]
@istvankleijn Yes, you can use `--ont-r10_dorado_hac_5khz` for `dna_r10.4.1.e8.2_400bps_hac@v4.3.0` basecalled data. 

We will release the v5.0.0 pre-trained model once the data is ready.

**Comment by lucy924** [comment]
Thank you for the clarification! out of curiosity, how long does it take to train a new model?
