### ISSUE TITLE
about v0.4.0 for calling indel

### ISSUE THREAD

**Issue by DayTimeMouse** [HKU-BAL/ClairS#39]
Hi,

Thank you for providing this tool.

I noticed that you have updated to a new version (0.4.0). I would like to ask if it supports Indel calling for PacBio Revio.

Additionally, for HiFi data, which do you recommend: minimap2 or pbmm2? I am also using deepsomatic to call SNP/Indel variants, and this tool suggests using pbmm2. 

I want to integrate the results from these two tools and wonder if the choice of alignment software needs to be consistent.

Best regards.

**Comment by aquaskyline** [comment]
v0.4.0 offers new models for ONT only. PacBio Revio model is scheduled for the next release.

ClairS has no preference on aligner, algorithm for PacBio, our benchmarks were done using alignments from minimap2.
